#pragma once

#define UPGL_MAX_BONES_PER_VERTEX 4
#define UPGL_CONSOLE_LOG_SIZE 256
#define UPGL_PROFILER_PLOT_POINTS 50U
#define UPGL_PROFILER_PLOT_INTERVAL_MS 300.f
#define UPGL_FIXED_UPDATE_STEP 1 / 60.f